article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticlesView.as_view(), name='articles_page'),
    path('add-article-comment', views.add_article_comment, name='add_article_comment_function'),
    path('cat/<category>', views.ArticlesView.as_view(), name='articles_by_category_page'),
    path('<slug>', views.ArticleDetailView.as_view(), name='article_detail_page'),
]

eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('order/', include('order_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_module/urls.py
from django.urls import path
from . import views


urlpatterns = [
        # for function based view :
    # path('', views.index_page, name='index_page')
    #---------------------------------------------------------
    path('', views.IndexPageView.as_view(), name='index_page'),
    path('about-us', views.AboutPageView.as_view(), name='about_us_page')
]

article_module/models.py
from django.db import models
from account_module.models import User
from jalali_date import datetime2jalali, date2jalali


#---------------------------------------------------------------------
# a model for article-categories in db
class ArticleCategory(models.Model):
    is_active = models.BooleanField(default=True, verbose_name='فعال')
    parent_category = models.ForeignKey(
        'ArticleCategory',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='دسته بندی والد'
    )
    title = models.CharField(max_length=100, verbose_name='نام')
    url_title = models.CharField(max_length=100, unique=True, verbose_name='عنوان در url')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقالات'
        verbose_name_plural = 'دسته بندی های مقالات'


#---------------------------------------------------------------------
# a model for articles in db
class Articles(models.Model):
    is_active = models.BooleanField(default=True, verbose_name='فعال')
    categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    title = models.CharField(max_length=100, verbose_name='عنوان')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر')
    slug = models.SlugField(
        max_length=200,
        db_index=True,
        allow_unicode=True,
        unique=True,
        verbose_name='عنوان در url'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_index=True,
        verbose_name='نویسنده',
        editable=False,
        null=True
    )
    created_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ایجاد')
    description = models.TextField(verbose_name='توضیحات')
    text = models.TextField(verbose_name='متن مقاله')

    def get_jalali_date(self):
        return date2jalali(self.created_date)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


#---------------------------------------------------------------------
# a model for comments in db
class ArticleComments(models.Model):
    is_active = models.BooleanField(default=False, verbose_name='نمایش')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, verbose_name='مقاله')
    parent = models.ForeignKey('ArticleComments',null=True, blank=True, on_delete=models.CASCADE, verbose_name='کامنت والد')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    text = models.TextField(verbose_name='متن کامنت')

    def __str__(self):
        return f'({self.article} - {self.user})'

    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'

article_module/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Articles, ArticleCategory, ArticleComments
from django.http import HttpResponse, HttpRequest


#------------------------------------------------------------------------
# to load articles and filter them by category
class ArticlesView(ListView):
    template_name = 'articles.html'
    model = Articles
    paginate_by = 3
    context_object_name = 'articles'

    def get_queryset(self):
        query = super().get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(categories__url_title__iexact=category_name, is_active=True)
        return query


#------------------------------------------------------------------------
# to load side-bar (categories)
def article_categories_component(request):
    categories = ArticleCategory.objects.filter(is_active=True, parent_category=None)
    context = {'categories': categories}
    return render(request, 'components/article_categories_component.html', context)


#------------------------------------------------------------------------
# to load article detail page
class ArticleDetailView(DetailView):
    template_name = 'article_detail.html'
    model = Articles
    context_object_name = 'article'

# to check if article is_active :
    def get_queryset(self):
        query = super().get_queryset()
        query = query.filter(is_active=True)
        return query

# to get comments :
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        article: Articles = kwargs.get('object')
        context['comments'] = ArticleComments.objects.filter(article_id=article.id, is_active=True, parent=None).prefetch_related('articlecomments_set').order_by('-create_date')
        context['comments_count'] = ArticleComments.objects.filter(article_id=article.id, is_active=True).count()
        return context


#------------------------------------------------------------------------
# to save comments in db
def add_article_comment(request: HttpRequest):
    if request.user.is_authenticated:
        article_id = request.GET.get('article_id')
        article_comment = request.GET.get('article_comment')
        parent_id = request.GET.get('parent_id')
        ArticleComments.objects.create(
            article_id=article_id,
            parent_id=parent_id,
            user_id=request.user.id,
            text=article_comment,
            is_active=True

        )
    return HttpResponse('end of function')

article_module/templates/components/article_categories_component.html
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>دسته بندی مقالات</h2>
        <div class="panel-group category-products" id="accordian"><!--category-productsr-->

            {% for category in categories %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            {% if category.articlecategory_set.all %}
                                <a data-toggle="collapse" data-parent="#accordian" href="#{{ category.url_title }}">
                                    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                    {{ category.title }}
                                </a>
                            {% else %}
                                <a href="{% url 'articles_by_category_page' category.url_title %}">
                                    <span class="badge pull-right"></span>
                                    {{ category.title }}
                                </a>
                            {% endif %}
                        </h4>
                    </div>
                    <div id="{{ category.url_title }}" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                                <li><a href="{% url 'articles_by_category_page' category.url_title %}"><b>تمام مقاله ها</b></a></li>
                                {% for sub_cat in category.articlecategory_set.all %}
                                	<li><a href="{% url 'articles_by_category_page' category=sub_cat.url_title %}"> {{ sub_cat.title }} </a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div><!--/category-productsr-->
    </div>
</div>